####  如果不使用nacos配置服务则可以放开一下注释，否则把一下配置放到nacos配置中心中;
####  dataID为spring.application.name 如果涉及多环境可以配置spring.profiles.active
####  此时dataID为{spring.application.name}-{spring.profiles.active}.{配置文件格式}
#server:
#  port: 9090
#spring:
#  cloud:
#    sentinel:
#      filter:
#        enabled: false
#      transport:
#        dashboard: 10.128.90.4:8080
#        port: 8719
#      eager: true
#    nacos:
#      discovery:
#        server-addr: 10.128.90.4:8848
#    gateway:
#      routes:
#        - id: demo-service
#          uri: lb://demo-service
#          predicates:
#            - Path=/demo-service/**
#        #gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，
#        #这个router将以服务名开头的请求路径转发到对应的服务
#      discovery:
#        locator:
#          enabled: true
#
#
#logging:
#  level:
#    org.springframework.cloud.gateway: debug
#    com.windmt.filter: debug