spring:
  redis:
    host: 10.128.90.4
    port: 6379
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: limit_route
          uri: http://localhost:9091
          predicates:
            - Path=/demo-service/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 3