####  如果不使用nacos配置服务则可以放开一下注释，否则把一下配置放到nacos配置中心中;
####  dataID为spring.application.name 如果涉及多环境可以配置spring.profiles.active
####  此时dataID为{spring.application.name}-{spring.profiles.active}.{配置文件格式}
#server:
#  port: 8080
#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.199.21:8848
#    gateway:
#      routes:
#        - id: demo-service
#          uri: lb://demo-service
#          predicates:
#            - Path=/demo-service/**
#          filters:
#            - name: RequestRateLimiter
#              args:
#                #令牌桶每秒填充平均速度
#                redis-rate-limiter.replenishRate: 1
#                #令牌桶上限
#                redis-rate-limiter.burstCapacity: 1
#                #使用SpEL表达式从Spring容器中获取限流对象
#                key-resolver: "#{@ipLimit}"
#            #- AddResponseHeader=X-Response-Default-Foo，Default-Bar
#        #gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，
#        #这个router将以服务名开头的请求路径转发到对应的服务
#      discovery:
#        locator:
#          enabled: true
#  #redis相关配置（限流使用）
#  redis:
#    host: 192.168.199.21
#    port: 6379
#    database: 0
#    password: 123456
#
#logging:
#  level:
#    org.springframework.cloud.gateway: debug
#    com.windmt.filter: debug